services:
  - type: web
    name: ecommerce-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    buildFilter:
      paths:
      - frontend/**
    envVars:
      - key: NODE_VERSION
        value: 22.16.0